variables:
  REGISTRY: registry.gitlab.com:4567
  REPO_ID: 58f8a9ca35e7e10900de8bbe
stages:
  - build
  - deploy
build:
  image: docker:latest
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/rishighan/rishighan-angular .
    - docker push $REGISTRY/rishighan/rishighan-angular
  only:
    - production
  tags:
    - docker
deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y -qq npm curl
    - npm install -g n
    - n stable
    - npm install -g stackahoy
    - stackahoy deploy -t $STACKAHOY_TOKEN -b production -r $REPO_ID --skip-delivery
  only:
    - production
  tags:
    - docker