# find a way to seed the mongo db
version: '3.0'
services:
  mongodb:
    build:
      context: ./
      dockerfile: mongo-seed/Dockerfile
  web:
    build: .
    command: node server.js
    volumes:
      - .:/usr/src/rishighan
    ports:
      - "80:8080"
    links:
      - mongodb
    environment:
      PORT: 8080 # this is optional, allows express to use process.env.PORT instead of a raw 3000
      DOCKER_MONGO_HOST:
