# find a way to seed the mongo db
version: '3.2'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-seed:
    build:
      context: ./
      dockerfile: mongo-seed/Dockerfile
    links:
      - mongodb
  web:
    build: .
    command: node server.js
    volumes:
      - .:/usr/src/rishighan
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      PORT: 3000 # this is optional, allows express to use process.env.PORT instead of a raw 3000
