#!/usr/bin/env node
let debug = require('debug')('rishighan-angular');
var app = require('../server.js');
app.set('port', process.env.PORT || 3000);

// Start Server on 3000
app.listen(3000, function () {
    console.log("Server listening on port 3000");
});